### ISSUE TITLE
There is no HUD button as described.

### ISSUE THREAD

**Issue by TheKrush** [League-of-Foundry-Developers/torch#13]
![image](https://user-images.githubusercontent.com/671500/152893756-d7360436-f6e7-41ee-b46d-59844a8e2512.png)

Can you include a screenshot in the readme where it's supposed to be located?

**Comment by lupestro** [comment]
Sorry for the delay in responding. It should be right above the elevation. Things to check:
First, if this is a player rather than a GM, did the GM check the module setting to enable user torches? 
Second, if you are playing D&D5e, do you actually have torches in your inventory or the Light or Dancing Lights spell?
(If not D&D5e, then it doesn't check your items, and you can just click the icon to turn it on and off.)

**Comment by lupestro** [comment]
Did you ever get this resolved?

**Comment by TheKrush** [comment]
Sorry yeah it's working now, not sure what happened.


*Keith Yates*
