### ISSUE TITLE
DnD5e Bullseye Lantern has incorrect dimensions

### ISSUE THREAD

**Issue by Fragmenri** [League-of-Foundry-Developers/torch#28]
Hello,
I just wanted to report that the Bullseye Lantern's value for dnd5e system are wrong.
![image](https://user-images.githubusercontent.com/117613562/201393977-c6bba91e-e7b8-49c8-82ae-0bec3d11638e.png)
It should be 60 bright and 120 dim light :
![image](https://user-images.githubusercontent.com/117613562/201394048-0bdf6302-5549-4c53-acef-ada974d006e4.png)

also RAW, rounded cone angle are supposed to be 1rad (or 57.3 degrees). With that, the specification from Basic rules is respected
![image](https://user-images.githubusercontent.com/117613562/201394632-445a9c41-fcff-4338-914b-846eac70651b.png)

**Comment by lupestro** [comment]
Good catch - the distances are a typo, a copy/paste from lamp that never got the distances updated in the editing.

As for the angle, good catch again. I read cone and pictured the familiar flat dunce-cap cone from high school math and highway work sites, whose shadow is a triangle. For that, 53 degrees and a tad is right. However, if it's the shape with a uniform distance from center to the edge, whose shadow is a circle segment - is that still called a cone? - then you have the classic picture defining a radian or about 57 degrees. The latter makes more sense for a spell or light beam limited by how far it reaches.

I'll fix both of those for my next update. Thanks for the heads up.

**Comment by lupestro** [comment]
I dug in a little further and the name for the shape in math is "spherical sector". A spherical sector whose radius equals the distance along its outside surface has an angle of 1 radian. 

Then I dug into D&D a little further and it says of a cone "a cone's width at a given point along its length is equal to that point's distance from the point of origin." (For length, in context, it appears they're talking about the line you have chosen to direct its effect along.) This description matches the behavior of a mathematical cone and not a spherical sector, even though the spherical sector makes more sense for what these things do materially in the game. 

So, as best I can tell, the 53 degrees is right according to the rules even though it makes less sense. I'll keep it at 53 but you can customize to 57 with my cheerful blessing. I'll fix the other two numbers, though. Does that work?

**Comment by lupestro** [comment]
Then it occurs to me that Foundry only does light radially, so there is no way that Foundry can cast light in a true cone, whatever the D&D rules actually say. The cone lets dim sight extend a little further into distant corners, while the 1 radian sector provides the extra help along the edges. By limiting the angle to 53 degrees but staying spherical, you get neither the width nor the depth. You see less. That hardly seems fair, does it?

So, for Foundry, because it only offers spherical light, I can break the rules slightly and offer 57 degrees as a consolation prize. If some GM really feels strongly about that -- maybe they've orchestrated their dungeon to keep their monsters just out of sight but closer than 60 feet -- they can override it. 

I think the bullseye lantern is the only cone-based light source in the literature, so this shouldn't be too controversial. Cones are more commonly used for spells with a template and the shape of a template isn't constrained to circular geometry.

**Comment by Fragmenri** [comment]
You are right, the bulleye is the only one.
Also about the cone thing, default foundry make cone as spherical sector (l
know these can be changed).
For a while, I was thinking that using spherical sector already stole some
diagonal reach, then keeping 53° was making cone template very small and
uneffective. At least, upping the default 53 to 57°, was a way to give back
some area to those type of spells.

But now i'm wondering. Since diagonale distance are inherently broken if we
keep the 5ft grid. Then it makes no sense to try to keep a cone properly
shaped. But then, sphere or circle should also become square. And the whole
template system becomes dull. I feel like if we want to keep actual
circular shape. Then it makes no sense to use actual cone as written. (Or
if so, we should make squared circle).
That's the only way to keep consistency and not nerf one template over the
other.

Then, if we keep sphere and circle, and thus keep spherical sector. Them
having 1 rad as angle make perfect sense.

But I agree, it more becomes "do you want to square your template or have
them circular ?" (And change you default foundry cone template angle
accordingly) than a "cone template should be that way !"

**Comment by lupestro** [comment]
This issue has been addressed in release v2.1.4.
