### ISSUE TITLE
Torch Button Missing For Half Of Players

### ISSUE THREAD

**Issue by PhluXx1** [League-of-Foundry-Developers/torch#30]
Half of my players are missing the torch button and cannot activate any light. When I as the DM try to do it for them it works normally.

**Comment by lupestro** [comment]
The way Torch works has changed for several systems to be based on inventory as it was before in D&D5e:

* It now automatically recognizes a variety of light sources
* The list of light sources can be configured to include new systems and light sources via a user-supplied JSON file. 
* A character with multiple light sources in his or her inventory can select which of them to use by right clicking on the torch icon. (In the previous version, in DnD5e, there were a fixed hierarchy of two spells and a torch.)
* In any system where Torch doesn't have any known light sources, a player gets a "self" light that they can toggle, much as the original system had it, so that Torch can still be used in any system, even those that don't support enumerating equipment.
* Finally the GM always has the power to flip on a "default" light of for player, even if they have no light sources.

Because some get the torch button and some don't, my initial guess would be that some of your users may not have acquired a recognized light source as equipment.

To help me help you:
* What system are you running?
* Do your players' characters  have the light sources in their inventory?
* If they have consumable light sources like torches or candles, do they have a non-zero quantity? (If they have a quantity of zero, the torch button will appear with a red line through it.)

**Comment by PhluXx1** [comment]
The issue was that they lacked a torch in their inventory. Is it possible to disable this requirement not seeing one in module settings?

![image](https://user-images.githubusercontent.com/72770484/205456921-222f5c18-8164-4501-ad43-8db8d964f6c6.png)

**Comment by lupestro** [comment]
That looks like the version of the module that last shipped for v9. Are you running v9 of Foundry?

I don't see us enhancing the capabilities for the module for v9. In v9, DnD5e was the only system that was inventory driven.  All the others worked more or less the way you want DnD5e to work. In DnD5e, it looked first for the Dancing Lights or Light cantrips and then for Torch equipment. If torches were found, using one decremented the inventory. When the final one was extinguished, you got a slash through the button and couldn't ignite more until you got more.

In the enhanced module for v10, there are a lot more options and opportunities, fulfilling the features that a lot of people asked for - more light sources on more systems, with different effects suitable to the source. The user can select which light source from their inventory they want to use, and the list is game-extensible.  Systems for which no specific light sources are known now provide a "self" light source with the dim/light values you set in the config, which approximates the level of support non-DnD5e systems got in v9. 

However, what we have for v10 today won't reduce any system with an inventory-driven approach to a non-inventory-driven approach. This just wasn't on our radar to consider. 

However, I can think of a clean way to do this for v10. It could be in-scope to use the user light sources JSON to tell it to ignore any light sources already defined for a system. I can't say when we might do this, though. I'd rather know first whether anything in v10 gives you a better way forward that would make this no longer a need.

**Comment by PhluXx1** [comment]
Yes, I'm still running the last version of 9 as I'm still waiting on some modules to get a v10 update. Thanks for the info it's a shame that's a lacking feature. Thanks.

**Comment by lupestro** [comment]
@PhluXx1 Have you had a chance to move up to v10 and more recent versions of Torch? Is everything working for you now?
