### ISSUE TITLE
PF2 support: Render buttons for Light Items

### ISSUE THREAD

**Issue by apoapostolov** [League-of-Foundry-Developers/torch#36]
On actors with RuleElements that can cast light, such as an Everburning Torch, these items have configured size, light color, and effect templates that are lost when using regular torch lights. Please consider adding support for rendering additional buttons for each item that can cast light in the Token HUD interface.

**Comment by lupestro** [comment]
The whole rule element system in PF2e is excellent. It integrates the business of light-bearing into the rest of the game rules. It makes possible things that Torch will never be able to touch, like spells that cast light among other effects. Due to rule elements, PF2e is as close as anything in Foundry has ever become to being a truly complete system.

Do "ordinary" light sources in PF2e have rule elements associated with them? I think there are actions like lighting and extinguishing a torch that can trigger rule elements. If it can be done, but only with work, I'd love to see a blog article on how to do this.  The only reason I know of not to use its mechanisms _rather than Torch_ to support light in that system, would be, perhaps, if the work to expose the capabilities in rule elements for these light sources hasn't been done. I would gladly use mechanisms built from the system itself rather than my own module in a system that supported it. 

Setting aside `sources.json`, which is purely data, Torch has almost no system-specific functional code. Exceptions: 
* It has a generic inventory mechanism (in topology.js). 40 lines of code use this mechanism to provide inventory for GURPS. 
* It has generic socket request handlers (in request.js) for token creation/deletion.  60 lines of code use this mechanism to support "Dancing Lights" (and half those lines are the properties of the token itself, one per line, so really about 30 lines functionally.)

These exist, at least in part, as working demonstrations of how people _could_ use these generic mechanisms to extend the module if they wished. 

Otherwise, everything is generic, by intention and design. I can't see spending a lot of effort to hybridizing Torch for any single system, especially when I suspect that system already has a mechanism that would seamlessly provide everything that Torch does, with Token HUD automatically providing light and extinguish actions.

However, this opens an interesting conversation and I would be happy to consider any rationale you might have to revisit the above line of reasoning.

**Comment by apoapostolov** [comment]
I am closing this issue as I finally understand how the source.json works and this issue needs to be an improvement in the PF2 support. I will open a new issue.
