### ISSUE TITLE
Small Error?

### ISSUE THREAD

**Issue by spikedshrike** [League-of-Foundry-Developers/torch#70]
Excellent module,, much used. Small point though: I could be wrong but I believe SWADE Flashlight should have an angle of 35, not 3. I have to change it every time I update your module. 

Hope this helps.

Flashlight: Small battery-operated flashlight with angled head.
Emits light in a cone template that eliminates darkness penalties to
attack any target within. Weight: 1/2 lbs.

  "swade": {
    "system": "swade",
    "topology": "standard",
    "quantity" : "quantity",
    "sources": {
      "Candle": {
        "name": "Candle",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          {"bright": 0, "dim": 2, "angle": 360}
        ]
      },
      "Flashlight": {
        "name": "Flashlight",
        "type": "equipment",
        "consumable": false,
        "states": 2,
        "light": [
          {"bright": 10, "dim": 10, "angle": 3}
        ]

**Comment by lupestro** [comment]
The world of beams, rays, and cones continues to be an adventure all its own. Unfortunately, I have to ask "Which source are you quoting for that description?"

When I open the "Flashlight" item in gear from the "SWADE Core Rules" Foundry module, it just says `10” beam`. My 2009 Explorer's edition is just about as terse. Deadlands Reloaded (c) 2005 is, of course, silent on the matter. That would be a Ghost Rock device. Rays and cones appear in SWADE, but beams are never defined as a technical term, as far as I know. It wouldn't be unreasonable to take it as a synonym for a ray, but, lacking any way to create a ray of light in Foundry wherever this comes into play in any system, I usually take a beam or ray to be like a very narrow cone 1 unit wide (1 " in SWADE) at the stated distance. 

* Approximating with a triangle (AD&D pencil geometry) uses a right triangle with half the beam width, doubling the resulting angle. `atan((1"/2)/10")*2` is about 5.7 degrees. 
* "Doing it right" by making a segment and applying a fraction of the circumference to 360 degrees is actually easier envelope math - no calculator needed for the tangent table. `360 degrees * (1"/(2*pi*10"))` = 5.8 degrees, about the same.
 
At the very least, I owe the players at least that 6th degree by rounding rather than truncating the result. :))

If it is indeed specified as a cone template of width = length in the current main Savage Worlds Adventurer's Edition book, then it's one radian or 53 degrees (not 6 and not 35), and I can correct for that, too, while thanking you for the updated information. If the quoted text is from an expansion or follow-on book you're using, then it will need to continue to be customized in "Additional Light Sources," since I really have to stick for system-wide values to base books only. 

In either case, I'll need to adjust the value, either a little or a lot, in the next drop. Let me know the source of your information, so I know what to do with it, and thanks for drawing this to my attention!

**Comment by spikedshrike** [comment]
Anything to help. TBH when set to 3 the torchlight is such a sliver on the screen it is no good to man or beast. I did assume at the time you had just missed a digit off, and went to 35 as a nice median point. Also it looked right on the table top :)

SWADE says 10" long and little else, which was not helpful. I use a torch in my daily job and the light spreads, so not a beam. The torchlight description I quoted comes from SWEX Weird War II and as I'm running an Achtung! Cthulhu campaign it looked good enough to me. The use of a cone is also replicated in SWEX Horror Companion for a UV Flashlight.  I never calculated the emitting angle of a cone so thought 35 was about right. However, after physically measuring it, it is more like 23. 

![Angular](https://github.com/League-of-Foundry-Developers/torch/assets/149544629/25df4016-e008-4612-abab-d1f271a5504e)

SWEXE Horror
UV Flashlight
Unlike regular flashlights, ultraviolet
flashlights do not give off visible light,
and thus are no use for illuminating an area
unless the user is wearing nightvision goggles.
However, they are an effective weapon against
vampires.
Use the Cone Template to represent the
UV beam. All targets within the template may
make an Agility roll at –2 to avoid it.

Thanks for the additional info, I had seen there was a setting in your module and now I know a little more on how to use it.

**Comment by spikedshrike** [comment]
Just FYI

![Both Precise and Angular](https://github.com/League-of-Foundry-Developers/torch/assets/149544629/74b94200-821e-4481-8c9d-891de1da2eb7)

**Comment by lupestro** [comment]
So this is a _third_ RPG cone definition. Hmmm.... Can't do that with light in Foundry, but we can look at several possibilities that'll work, based solely on the width of the beam at the stated distance. `360/(2*pi) * (W/L)` =  `57.3 degrees * W/L`) 

I was using 1" beam width at 10", but this is a 3" beam width at 7.5", so 23 degrees. The shape is different, but if you keep the distance at 10" (as per the RAW) and apply 23 degrees, your beam width at distance is 4".  That's a lot of extra visible area. 3" at 10" is more like 17 degrees. That would run a little low on visible area. So based on all that, 19 or 20 degrees will probably illuminate the same amount of space as the SWADE precise cone. 

Nonetheless, the base book, for better or worse, says 10" beam, so the (admittedly more sensible) 20 degrees will need to be a house rule in your additional light sources.

**Comment by lupestro** [comment]
This afternoon, I finally shipped the adjustments I made back in November, going from 3 to 6 degrees on both SWADE and GURPS. The changes are in 2.11.1. The big change in this release was setting up github actions that should make releasing stuff less of an error-prone chore. With easier, cleaner releases, I'm far less likely to procrastinate on the endgame this dreadfully in the future. 

However, your 20 degrees is still going to be a house rule, so this probably doesn't help your situation. Let me know if you're good with me closing this issue.
