### ISSUE TITLE
Not found: torch-v2.12.0.zip

### ISSUE THREAD

**Issue by skald1** [League-of-Foundry-Developers/torch#73]
Console during install on Foundry v11 b315:
caught (in promise) Error: An unexpected error occurred when downloading file https://github.com/League-of-Foundry-Developers/torch/releases/download/v2.12.0/torch-v2.12.0.zip: Not Found

Link is dead

**Comment by lupestro** [comment]
Sorry about that - I was in build production hell for a few hours today, but it was perhaps in a good cause.  I've finally got some GitHub actions in play providing release automation that should make this all a lot easier to do consistently and reliably. Hence, I won't be repeating November's "work complete but never getting around to release until February because it's so painful." That's a new standard of procrastination, even for me.

See if updating now comes up with 2.11.1. If it's still insisting on 2.12.0, let me know. Also, let me know how 2.11.1 works out for you.

**Comment by skald1** [comment]
Now shows Version 2.11.0 in the Install Module, not 2.11.1
![image](https://github.com/League-of-Foundry-Developers/torch/assets/2029202/db599b34-ac33-4252-a4fa-ea1bf737bdeb)

- Installs successfully
- Once in Foundry, version shows 2.11.1 in Module Management
- Operates as expected.

THANKS! :)

**Comment by lupestro** [comment]
Yeah I hadn't published the admin side yet - figured since you were interested, I'd see what I hear from you first. I'll go do that now.

**Comment by skald1** [comment]
No worries, and thanks much!
