### ISSUE TITLE
Wrong animation type

### ISSUE THREAD

**Issue by AetherianRPG** [League-of-Foundry-Developers/torch#77]
Even though "torch" is set as animation type for most custom light sources, when a light source is turned on the "flickering light" animation is set instead.

![image](https://github.com/League-of-Foundry-Developers/torch/assets/68928934/a77c2ab6-c153-45e2-b740-ae02ce1fc2a4)

![image](https://github.com/League-of-Foundry-Developers/torch/assets/68928934/4dbb3c89-23c4-478e-b519-ee3e88f7829d)

**Comment by lupestro** [comment]
Sometimes the display names in the UI don't match the underlying names in the Foundry code: 
```html
<select name="light.animation.type">
    <option value="">None</option>
    <option value="flame">Torch</option>
    <option value="torch">Flickering Light</option>
    <option value="revolving">Revolving Light</option>
    <option value="siren">Siren Light</option>
    <option value="pulse">Pulse</option>
    <option value="chroma">Chroma</option>
    <option value="wave">Pulsing Wave</option>
    <option value="fog">Swirling Fog</option>
    <option value="sunburst">Sunburst</option>
    <option value="dome">Light Dome</option>
    <option value="emanation">Mysterious Emanation</option>
    <option value="hexa">Hexa Dome</option>
    <option value="ghost">Ghostly Light</option>
    <option value="energy">Energy Field</option>
    <option value="roiling">Roiling Mass</option>
    <option value="hole">Black Hole</option>
    <option value="vortex">Vortex</option>
    <option value="witchwave">Bewitching Wave</option>
    <option value="rainbowswirl">Swirling Rainbow</option>
    <option value="radialrainbow">Radial Rainbow</option>
    <option value="fairy">Fairy Light</option>
    <option value="grid">Force Grid</option>
    <option value="starlight">Star Light</option>
    <option value="smokepatch">Smoke Patch</option>
</select>
```
We store the values rather than the display names in the JSON - values are localization agnostic - so, yes, counterintuitively, everything that "says" torch isn't using the Torch animation. 

The existing lighting settings are really admittedly bland. I didn't want to dictate anything controversial unilaterally, but I am very open to having a few DnD5e users recommend better default lighting for each of the items. Anything five active players can agree upon is probably a really good improvement. :) The same goes for any other game system. 

If you want better default torch lighting for a system and there isn't a PR on the topic, open one. Pig-pile on the one PR with comments - play nice ;) and don't open a second PR if things aren't going your way. I'll be glad to commit to whatever seems to get a broad consensus.

**Comment by lupestro** [comment]
I supplied clarifying text in the README.md for 2.13.0 for the confusing animation types for Torch ("flame") and Flickering Light ("torch") animations.
